Feature/rbac tx exposure
hashed-io/hashed-substrate pull request #375
Opened 2023-02-27 20:39 UTC by Dreyhh

# Expose some RBAC functions

## Overview

Allows for the sudo account to add/remove roles and permissions across pallets

### Tickets

List the tickets of the PR linked
- [ ] Fix #352 

## Implementation notes

Makes public some helper functions of the RBAC pallet

## Test coverage

Since the "new" functions are just wrappers of already existing functions, we only needed to add tests for verifying the sudo account.

2023-03-01 17:50 UTC, didiermis requested changes
I created another ticket to add the missing events because that change isn't part of the scope of this one.
#378

2023-03-01 17:50 UTC, didiermis commented on pallets/fruniques/src/mock.rs
> +	type SudoOrigin = EnsureRoot<Self::AccountId>;
Following the standard we're using, update the:
```rust
type SudoOrigin = EnsureRoot<Self::AccountId>;
```
to
```rust
type RemoveOrigin = EnsureRoot<Self::AccountId>;
```
in the mock & test files.

See the following example:
`https://github.com/hashed-io/hashed-substrate/blob/7f1a8effbbd35994b3c803674b5f3e0847ef741a/pallets/fruniques/src/mock.rs#L63`

2023-03-01 17:50 UTC, didiermis commented on pallets/fund-admin/src/mock.rs
> +	type SudoOrigin = EnsureRoot<Self::AccountId>;
Following the standard we're using, update the:
```rust
type SudoOrigin = EnsureRoot<Self::AccountId>;
```
to
```rust
type RemoveOrigin = EnsureRoot<Self::AccountId>;
```
in the mock & test files.

See the following example:
`https://github.com/hashed-io/hashed-substrate/blob/7f1a8effbbd35994b3c803674b5f3e0847ef741a/pallets/fruniques/src/mock.rs#L63`

2023-03-01 17:50 UTC, didiermis commented on pallets/gated-marketplace/src/mock.rs
> +	type SudoOrigin = EnsureRoot<Self::AccountId>;
Following the standard we're using, update the:
```rust
type SudoOrigin = EnsureRoot<Self::AccountId>;
```
to
```rust
type RemoveOrigin = EnsureRoot<Self::AccountId>;
```
in the mock & test files.

See the following example:
`https://github.com/hashed-io/hashed-substrate/blob/7f1a8effbbd35994b3c803674b5f3e0847ef741a/pallets/fruniques/src/mock.rs#L63`

2023-03-01 17:50 UTC, didiermis commented on pallets/rbac/src/lib.rs
> +		type SudoOrigin: EnsureOrigin<Self::RuntimeOrigin>;
Following the standard we're using, update the:
```rust
		type SudoOrigin: EnsureOrigin<Self::RuntimeOrigin>;
```
to
```rust
		type RemoveOrigin: EnsureOrigin<Self::RuntimeOrigin>;
```
WARNING: The above comments were for the mock.rs files
in the lib.rs files, 

See the following example:
`https://github.com/hashed-io/hashed-substrate/blob/7f1a8effbbd35994b3c803674b5f3e0847ef741a/pallets/fruniques/src/lib.rs#L35`

2023-03-01 17:50 UTC, didiermis commented on pallets/rbac/src/lib.rs
> +		// TODO: Add docs (here and in readme)
Please update the readme.md: Add a description for the newly exposed extrinsics. You don't need to worry about the CLI part; I could update that part.

2023-03-01 17:50 UTC, didiermis commented on runtime/src/lib.rs
> +	type SudoOrigin = EitherOfDiverse<
Following the standard we're using, update the:
```rust
	type SudoOrigin = EitherOfDiverse<
		EnsureRoot<AccountId>,
		pallet_collective::EnsureProportionAtLeast<AccountId, CouncilCollective, 3, 5>,
	>;
```
to
```rust
	type RemoveOrigin = EitherOfDiverse<
		EnsureRoot<AccountId>,
		pallet_collective::EnsureProportionAtLeast<AccountId, CouncilCollective, 3, 5>,
	>;
```
WARNING:
in the runtime lib.rs file

See the following example:
`https://github.com/hashed-io/hashed-substrate/blob/7f1a8effbbd35994b3c803674b5f3e0847ef741a/runtime/src/lib.rs#L573`

2023-03-01 17:50 UTC, didiermis commented on parachain-runtime/src/lib.rs
> +	type SudoOrigin = EnsureRoot<AccountId>;
Following the standard we're using, update the:
```rust
	type SudoOrigin = EnsureRoot<AccountId>;
```
to
```rust
	type RemoveOrigin = EnsureRoot<AccountId>;
```

2023-03-01 17:50 UTC, didiermis commented on pallets/rbac/src/mock.rs
> +	type SudoOrigin  = EnsureRoot<Self::AccountId>;
Following the standard we're using, update the:
```rust
	type SudoOrigin = EnsureRoot<AccountId>;
```
to
```rust
	type RemoveOrigin = EnsureRoot<AccountId>;
```

2023-03-01 17:50 UTC, didiermis commented on pallets/rbac/src/lib.rs
> +			// TODO: emit event on success
Remove this comment because the "create_and_set_roles" helper function already emits an event on success.

2023-03-01 17:50 UTC, didiermis commented on pallets/rbac/src/lib.rs
> +			// TODO: emit event on success
Please don't delete this comment; I saw that multiple helper functions are missing events. We could fix it in another ticket.

2023-03-13 15:49 UTC, Dreyhh commented on pallets/fruniques/src/mock.rs
> +	type SudoOrigin = EnsureRoot<Self::AccountId>;
Done

2023-03-13 15:49 UTC, Dreyhh commented on pallets/fund-admin/src/mock.rs
> +	type SudoOrigin = EnsureRoot<Self::AccountId>;
Done

2023-03-13 15:50 UTC, Dreyhh commented on pallets/gated-marketplace/src/mock.rs
> +	type SudoOrigin = EnsureRoot<Self::AccountId>;
Done

2023-03-13 15:50 UTC, Dreyhh commented on pallets/rbac/src/lib.rs
> +			// TODO: emit event on success
Done

2023-03-13 15:50 UTC, Dreyhh commented on pallets/rbac/src/lib.rs
> +		// TODO: Add docs (here and in readme)
Done

2023-05-03 17:20 UTC, didiermis commented
@amatsonkali When a permission is removed, either from a role or a pallet, it should also be removed from the users who have it. I believe this change is necessary to ensure that users do not have unnecessary permissions after they have been removed from a role or pallet. If the corresponding permissions are not removed from the affected users, they could continue to have access to functions or resources they should no longer have access to. Therefore, it is recommended to include an update routine that identifies the users who have the removed permission and removes it from their corresponding user profile.

2023-05-03 17:27 UTC, didiermis commented
LGTM! :+1: 
Great job @Dreyhh & @amatsonkali

2023-05-03 17:31 UTC, merged